name: PR Sanity Check

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          rm -rf node_modules package-lock.json && npm install
          npm install

      - name: Lint check
        run: |
          npm run lint
